# Environment only (not a package). For: julia --project=. test_hesitancy_aware.jl

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ReactiveMP = "a194aa59-28ba-4574-a09c-4a745416d6e3"
Rocket = "df971d30-c9d6-4b37-b8ff-e965b2cb3a40"
RxInfer = "86711068-29c9-4ff7-b620-ae75d7495b3d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
